name:                WordWrap
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/CarstenKoenig/DOS2018/tree/master/Katas/WordWrap#readme
license:             OtherLicense
license-file:        LICENSE
author:              Carsten König
maintainer:          Carsten@gettingsharper.de
category:            Your Projects Category
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - mtl
    - containers

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - tests
    dependencies:
      - hspec == 2.*
      - QuickCheck
      - WordWrap
    build-tools: hspec-discover
